"""empty message

Revision ID: 364cc60eacde
Revises: 075c31a3d3d2
Create Date: 2024-07-20 16:32:07.773092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364cc60eacde'
down_revision = '075c31a3d3d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image_url', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
