"""book list feature

Revision ID: 548bee1c6cd5
Revises: caaaee5da6ff
Create Date: 2024-07-15 16:20:50.629090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '548bee1c6cd5'
down_revision = 'caaaee5da6ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_books',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'book_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_books')
    # ### end Alembic commands ###
